encoding: UTF-8

force_polling: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "press"
    values:
      layout: "release"

collections:
  software:
    output: false
  press:
    output: true
  usecases:
    output: true

sass:
    style: :compressed

kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from

array: []
